### ISSUE TITLE
Way too spammy

### ISSUE THREAD

**Issue by N-kay** [Kivou-2000607/yata-bot#24]
Actually useful information is drowned out in a sea of never ending messages that just keep piling on.

You should really think about reducing the amount of messages sent, and edit already sent messages instead.

Example: Keep a single embed with a list of all ready OCs, updating it as you go instead of constantly spamming the newest update.

> OC 1 is ready
> OC 2 is ready
> OC 2 is not ready
> OC 2 is ready
> OC 2 is not ready
> OC 2 is ready

You can't tell which OCs are ready at a glance. Most people would ignore the messages alltogether after a while.

If immediate attention is desired, mention a role inside the embed. If it's already mentioned, remove and add it again for a renewed ping.

Another example: One embed per chain. Ping on creation. Throw a link to the chain on the yata website on there. Update it as you go. Ping on certain times left. Final update when chain is done. Maybe delete when chain goes nowhere.

**Comment by Kivou-2000607** [comment]
Thanks for the input! I appreciate.
I'll see what I can do about it. It's true that especially with elimination the OC is really spammy.

**Comment by Kivou-2000607** [comment]
I've implemented a beta for the OC.
You can toggle it on the dashboard in administration -> other settings and do a `!sync` after.

If should be more or less what you proposed.
